{
  "test_case_name": "linux_auth_failed_test_case",
  "description": "linux_auth_failed_test_case",
  "test_specification": {
    "event": {
      "original_string": "2022-11-09T10:27:00.570949+05:30 ulaa-u20-aio sudo: pam_unix(sudo:auth): authentication failure; logname=test uid=1001 euid=0 tty=/dev/pts/4 ruser=test rhost=  user=test",
      "source_type": "linux_syslog",
      "timestamp": 1667972206479
    }
  },
  "assertions": [
    {
      "assertion_type": "path_and_value_matches",
      "json_path": "original_string",
      "expected_pattern": "authentication",
      "negated_pattern": false,
      "active": true
    }
  ],
  "author": "siembol",
  "version": 1,
  "config_name": "linux_syslog_failed_auth"
}